<?xml version="1.0"?>
<!-- Comment -->
<!DOCTYPE APP_CONTENT
     [
     <!ELEMENT APP_CONTENT (INTERNALS)*>
     <!ELEMENT INTERNALS (NAME, DESCRIPTION, DIR, BROADCAST, APPS_MARKET, VERSION)>
     <!ELEMENT NAME (#PCDATA)>
     <!ELEMENT DESCRIPTION (#PCDATA)>
	 <!ELEMENT DIR (#PCDATA)>
	 <!ELEMENT BROADCAST (#PCDATA)>
	 <!ELEMENT APPS_MARKET (#PCDATA)>
	 <!ELEMENT VERSION (#PCDATA)>
     ]
>
<APP_CONTENT>
     <INTERNALS>
          <NAME> Обозреватель картинок </NAME>
          <DESCRIPTION> Данная программа поможет вам выполнять всевозможные действия с Вашими файлами и подключенными устройствами. </DESCRIPTION>
		  <DIR> imgview </DIR>
		  <START> 1 </START>
		  <APPS_MARKET> #imgview </APPS_MARKET>
		  <VERSION> 1.0 </VERSION>
     </INTERNALS>
</APP_CONTENT>