<?xml version="1.0"?>
<!-- Comment -->
<!DOCTYPE APP_CONTENT
     [
     <!ELEMENT APP_CONTENT (INTERNALS)*>
     <!ELEMENT INTERNALS (NAME, DESCRIPTION, DIR, BROADCAST, APPS_MARKET, VERSION, START)>
     <!ELEMENT NAME (#PCDATA)>
     <!ELEMENT DESCRIPTION (#PCDATA)>
	 <!ELEMENT DIR (#PCDATA)>
	 <!ELEMENT BROADCAST (#PCDATA)>
	 <!ELEMENT APPS_MARKET (#PCDATA)>
	 <!ELEMENT VERSION (#PCDATA)>
	 <!ELEMENT START (#PCDATA)>
     ]
>
<APP_CONTENT>
     <INTERNALS>
          <NAME> Workcast </NAME>
          <DESCRIPTION> Пользуйтесь своим xCloud транслируя рабочую зону на экран. </DESCRIPTION>
		  <DIR> hdmibrd </DIR>
		  <BROADCAST> 1 </BROADCAST>
		  <START> 0 </START>
		  <APPS_MARKET> #hdmibrd </APPS_MARKET>
		  <VERSION> 1.0 </VERSION>
     </INTERNALS>
</APP_CONTENT>